from django.db import models

class PlayerPerGameStats(models.Model):
    Rank = models.IntegerField()
    Player = models.CharField(max_length=100)
    Position = models.CharField(max_length=10)
    Age = models.IntegerField()
    Team = models.CharField(max_length=5)
    GamesPlayed = models.IntegerField(default=0)
    GamesStarted = models.FloatField(null=True)
    MinutesPlayed = models.FloatField(default=0)
    FieldGoalsMade = models.FloatField(default=0)
    FieldGoalsAttempted = models.FloatField(default=0)
    FieldGoalPercentage = models.FloatField(default=0, null=True)
    ThreePointersMade = models.FloatField(default=0)
    ThreePointersAttempted = models.FloatField(default=0)
    ThreePointPercentage = models.FloatField(default=0, null=True)
    TwoPointersMade = models.FloatField(default=0)
    TwoPointersAttempted = models.FloatField(default=0)
    TwoPointPercentage = models.FloatField(default=0, null=True)
    EffectiveFieldGoalPercentage = models.FloatField(default=0, null=True)
    FreeThrowsMade = models.FloatField(default=0)
    FreeThrowsAttempted = models.FloatField(default=0)
    FreeThrowPercentage = models.FloatField(default=0, null=True)
    OffensiveRebounds = models.FloatField(default=0)
    DefensiveRebounds = models.FloatField(default=0)
    TotalRebounds = models.FloatField(default=0)
    Assists = models.FloatField(default=0)
    Steals = models.FloatField(default=0)
    Blocks = models.FloatField(default=0)
    Turnovers = models.FloatField(default=0)
    PersonalFouls = models.FloatField(default=0)
    Points = models.FloatField(default=0)
    Year = models.IntegerField()

